/* Generated by Yosys 0.10.0 (git sha1 UNKNOWN, clang 12.0.0 -fPIC -Os) */

module crc4_check(i_data, i_poly, o_crc);
  wire [7:0] crc_tmp;
  wire [31:0] i;
  input [3:0] i_data;
  input [1:0] i_poly;
  output [3:0] o_crc;
  wire [7:0] poly_tmp;
  wire [3:0] s_crc;
  wire [4:0] s_poly;
  assign crc_tmp = { i_data, 2'hx, i_poly };
  assign i = 32'd4294967295;
  assign o_crc = { 2'hx, i_poly };
  assign poly_tmp = 8'h0x;
  assign s_crc = { 2'hx, i_poly };
  assign s_poly = 5'hxx;
endmodule

module u1intou2(i_argA, o_result);
  input [1:0] i_argA;
  output [1:0] o_result;
  assign o_result[0] = i_argA[0] | i_argA[1];
  assign o_result[1] = 1'h0;
endmodule
